name: Test CI

on:
  pull_request:
    branches: ["*"]
    paths:
      - ".github/workflows/ci_test.yml" # this file
      - "go.mod"
      - "go.sum"
      - "Makefile"
      - "generate/**/*"
      - "src/**/*"
  schedule:
    - cron: "37 13 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Generate go code from go:generate comments
        run: make install

      - name: Build project
        run: make compile

  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Generate go code from go:generate comments
        run: make install

      - name: Test units (w/o engines)
        run: make test

  test-engines:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Generate go code from go:generate comments
        run: make install

      - name: Test units (only engines)
        run: make test-engines

  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Generate go code from go:generate comments
        run: make install

      - name: Run linter
        uses: golangci/golangci-lint-action@v5
        with:
          version: latest
          skip-pkg-cache: true
          args: --timeout=5m
